"""Simple Pipeline video-script schema.

This schema is intentionally weaker than EDS. It represents the baseline's
direct MLLM explanation script before conversion to a minimal renderable EDS.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


SimpleSegmentType = Literal["problem_overview", "step", "answer", "recap"]
SimpleStatus = Literal["passed", "failed"]


class SimpleVideoModel(BaseModel):
    """Base class for strict Simple Pipeline artifacts."""

    model_config = ConfigDict(extra="forbid")

    @staticmethod
    def _ensure_non_empty(value: str) -> str:
        if not value or not value.strip():
            raise ValueError("must be a non-empty string")
        return value.strip()


class SimpleVideoSegment(SimpleVideoModel):
    """One baseline video segment generated by a direct MLLM call."""

    segment_id: str
    segment_type: SimpleSegmentType
    narration: str
    display_text: str
    formula: str | None = None
    estimated_duration_ms: int = Field(default=7000, ge=1000)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("segment_id", "narration", "display_text")
    @classmethod
    def required_strings_must_be_non_empty(cls, value: str) -> str:
        return cls._ensure_non_empty(value)

    @field_validator("formula")
    @classmethod
    def empty_formula_becomes_none(cls, value: str | None) -> str | None:
        if value is None:
            return None
        cleaned = value.strip()
        return cleaned or None


class SimpleVideoQualityReport(SimpleVideoModel):
    """Lightweight quality report for baseline parsing and normalization."""

    valid: bool
    status: SimpleStatus
    checked_segment_count: int = Field(ge=0)
    errors: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)


class SimpleVideoScript(SimpleVideoModel):
    """Direct-MLLM baseline script before minimal EDS conversion."""

    schema_version: str = "SIMPLE_VIDEO-1.0"
    problem_id: str
    source_image: str
    problem_text: str
    final_answer: str
    segments: list[SimpleVideoSegment] = Field(default_factory=list, min_length=1)
    quality_report: SimpleVideoQualityReport
    metadata: dict[str, Any] = Field(default_factory=dict)

    @field_validator("schema_version", "problem_id", "source_image", "problem_text", "final_answer")
    @classmethod
    def required_strings_must_be_non_empty(cls, value: str) -> str:
        return cls._ensure_non_empty(value)


def validate_simple_video_script_dict(data: dict[str, Any]) -> SimpleVideoScript:
    """Validate a SimpleVideoScript dictionary."""

    return SimpleVideoScript.model_validate(data)
